In [24]:
import pandas as pd
data = pd.read_csv("Data/activity_readings.csv")
df = pd.DataFrame(data)
data2 = pd.read_csv("Data/stations.csv")
df2 = pd.DataFrame(data2)

In [7]:
df.head()

  event_id         source_id             timestamp value
0   e00001   station-east-01  2026-09-09T08:00:00Z  26.6
1   e00002   station-east-02  2026-09-09T08:00:00Z  42.1
2   e00003  station-north-01  2026-09-09T08:00:00Z  44.5
3   e00004  station-north-02  2026-09-09T08:00:00Z  62.5
4   e00005  station-south-01  2026-09-09T08:00:00Z  93.4

In [11]:
df.shape

(2092, 4)

In [8]:
df.columns

Index(['event_id', 'source_id', 'timestamp', 'value'], dtype='str')

In [9]:
df['timestamp'].sort_index

<bound method Series.sort_index of 0       2026-09-09T08:00:00Z
1       2026-09-09T08:00:00Z
2       2026-09-09T08:00:00Z
3       2026-09-09T08:00:00Z
4       2026-09-09T08:00:00Z
                ...
2087    2026-09-09T12:19:00Z
2088    2026-09-09T12:19:00Z
2089    2026-09-09T12:19:00Z
2090    2026-09-09T12:19:00Z
2091    2026-09-09T12:19:00Z
Name: timestamp, Length: 2092, dtype: str>

In [15]:
df[df['event_id'].isna()]

    event_id         source_id             timestamp  value
283      NaN  station-north-01  2026-09-09T08:35:00Z   41.2
424      NaN   station-west-01  2026-09-09T08:52:00Z  118.9

In [16]:
df[df['source_id'].isna()]

    event_id source_id             timestamp  value
554   e00555       NaN  2026-09-09T09:09:00Z   58.0
691   e00692       NaN  2026-09-09T09:26:00Z  101.4

In [17]:
df[df['timestamp'].isna()]

     event_id         source_id timestamp value
1107   e01108  station-south-01       NaN  99.5

In [22]:
df[df['value'].isna()]

     event_id         source_id             timestamp value
1247   e01248   station-west-02  2026-09-09T10:34:00Z   NaN
1519   e01520  station-south-02  2026-09-09T11:08:00Z   NaN

In [ ]:
df2.columns

Index(['station_id', 'name', 'sector', 'status'], dtype='str')

In [ ]:
df.dtypes

event_id     str
source_id    str
timestamp    str
value        str
dtype: object

: